### ISSUE TITLE
naming conventions

### ISSUE THREAD

**Issue by pelikhan** [kaku111/pxt-tobbieII#3]
Follow MakeCode naming conventions: https://makecode.com/extensions/naming-conventions
https://github.com/kaku111/pxt-tobbieII/blob/923e9db9a90667ef6c20d22700cc1f2a7b8df672/main.ts#L212

**Comment by kaku111** [comment]
I have modified it, according to MakeCode naming conventions. thanks!
ex:  stopwalk()--> stopWalk(), stopturn()-->stopTurn()... ect.
