### ISSUE TITLE
enforce vibrate bounds

### ISSUE THREAD

**Issue by pelikhan** [kaku111/pxt-tobbieII#4]
The user may enter any number via typescript.

https://github.com/kaku111/pxt-tobbieII/blob/923e9db9a90667ef6c20d22700cc1f2a7b8df672/main.ts#L270

**Comment by kaku111** [comment]
I have limited the variable "time"
![vibrate_times](https://user-images.githubusercontent.com/35320401/55277486-b8cb0700-533b-11e9-9b81-47dc546d2bcf.jpg)
 range from 1 to 100.
